# This file was *autogenerated* from the file create_parameter_files.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21)
import csv
directory = 'parameter_files/'

def chunks(lst, chunk_size):
	"""
	Splits a list into chunks
	"""
	final_list = []
	i = _sage_const_0 
	list_len = len(lst)
	while i < list_len:
		final_list.append(lst[i:i+chunk_size])
		i += chunk_size
	return final_list

def write_params_to_file(directory, sffx, lst):
	"""
	Writes the paramters to a file
	"""
	data_file = open('%sparams_%i.csv' % (directory, sffx), 'w')
	csv_wrtr = csv.writer(data_file)
	for row in lst:
		csv_wrtr.writerow(row)
	data_file.close()


rs = [(float(r11/_sage_const_5 ), float(r12/_sage_const_5 )) for r11 in range(_sage_const_1 ,_sage_const_6 ) for r12 in range(_sage_const_1 ,_sage_const_6 -r11)]
Ls = [i/_sage_const_10  for i in range(_sage_const_1 ,_sage_const_21 )]
mus = [_sage_const_1 ]
ns = [_sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ]

all_parameter_sets = list(cartesian_product_iterator([ns, ns, mus, mus, rs, rs, Ls, Ls]))
chunk_size = int(len(all_parameter_sets)/_sage_const_20 )
parameter_sets_chunks = chunks(all_parameter_sets, chunk_size)


for i in range(len(parameter_sets_chunks)):
	write_params_to_file(directory, i, parameter_sets_chunks[i])
